### PR TITLE
restructure project & reworked data models

### PR DESCRIPTION
**Pull request by shpilevsky-bsuir-labs**
PR for 2nd lab

### CODE REVIEW

**Review by katetushkan — COMMENTED** [review]
Good, It's 10.

**Comment by shpilevsky-bsuir-labs** [comment]
> Good, It's 10.

if i'm not mistaking, once during a lab you said, that you choose 3 features which we should implement in a project. isn't it ?)
obviously, i could dream it)

**Comment by katetushkan** [comment]
> > Good, It's 10.
> 
> if i'm not mistaking, once during a lab you said, that you choose 3 features which we should implement in a project. isn't it ?) obviously, i could dream it)

Yes, after ur 3rd lab)

**Comment by shpilevsky-bsuir-labs** [comment]
> > > Good, It's 10.
> > 
> > if i'm not mistaking, once during a lab you said, that you choose 3 features which we should implement in a project. isn't it ?) obviously, i could dream it)
> 
> Yes, after ur 3rd lab)

I see, thanks

**Pull request merged**
